version: "3.2"

services:
  redis:
    # image: "redis/redis-stack:7.0.6-RC2"
    image: "redis/redis-stack:latest"
    expose:
      - "6379"
      - "8001"
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf

volumes:
  redis-data:
  redis-conf:
